###REGISTER NEW USER
POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "registro hecho desde user.http ajajaja",
    "email": "joaquin@gmail.com",
    "password": "contra"
}

###LOGIN CREATED USER
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "joaquin@gmail.com",
    "password": "contra"
}